normalizedCounts=read.table(".normalizedCounts.xls",header=T,sep = "\t")
dim(normalizedCounts)
normMatrix <- as.matrix(normalizedCounts[,2:1])
samplesCorr <- cor(normMatrix,method="pearson")
write.table(samplesCorr,file=".pearsonCorrelationAmongSamples.xls",sep="\t",col.names=NA,eol = "\n",dec = )
PC <- prcomp(normMatrix,scale.=T)
pdf(".proportionOfVariance.pdf")
screeplot(PC)
dev.off()
pdf(".samplesPCA.pdf")
rot <- PC$r
plot(rot[,1],rot[,2],ylab="PC2",xlab="PC1",main=c("PCA"),pch=16,col=c())
abline(h=0,v=mean(rot[,1],h=0,col="grey"))
text(rot[,1],rot[,2],label=rownames(rot),font=0,col=c(),cex=0.75,pos=ifelse(rot[,1]<mean(rot[,1]),yes=4,no=2))
dev.off()
# 3D PCA
library("scatterplot3d")
pdf(".samplesPCA3D_60.pdf")
plot3d<-scatterplot3d(rot[,1],rot[,2],rot[,3],bg="black", ylab="PC2", xlab="PC1",zlab="PC3",main=c("PCA"),pch=20,type="h",angle=60)
text(plot3d$xyz.convert(rot[,1],rot[,2],rot[,3]),label=rownames(rot),font=0,col=c(),cex=0.75,pos=ifelse(rot[,1] < mean(rot[,1]), yes=4, no=2))
dev.off()
# 3D PCA
library("scatterplot3d")
pdf(".samplesPCA3D_minus60.pdf")
plot3d<-scatterplot3d(rot[,1],rot[,2],rot[,3],bg="black", ylab="PC2", xlab="PC1",zlab="PC3",main=c("PCA"),pch=20,type="h",angle=-60)
text(plot3d$xyz.convert(rot[,1],rot[,2],rot[,3]),label=rownames(rot),font=0,col=c(),cex=0.75,pos=ifelse(rot[,1] < mean(rot[,1]), yes=4, no=2))
dev.off()
